# Generated by Django 4.2.29 on 2026-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customeruser_parol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='parol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
