# Generated by Django 5.2.11 on 2026-05-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_activationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='parol',
        ),
    ]
