# Generated by Django 4.2.29 on 2026-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(upload_to='Products/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
